# Generated by Django 3.2.2 on 2021-05-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Data',
        ),
    ]
